title: Designing Defensible Dissertation Research
author: Timothy D. Bowman

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/tdbowman/lis971-ebook
  branch: main

html:
  use_repository_button: true
  use_issues_button: false
  home_page_in_navbar: true

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
    - tasklist
